version: '3.8'
networks:
  web:
    external: true
  smart-home:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1
services:
  homeassistant:
    depends_on:
      zigbee2mqtt:
        condition: service_started
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /volume1/smart-home/homeassistant/config:/config
#    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      TZ: Europe/Warsaw
    restart: unless-stopped
    ports:
      - "8123:8123"
    networks:
      web:
      smart-home:
        ipv4_address: 192.168.55.10

  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    container_name: mqtt
    volumes:
      - "/volume1/smart-home/mosquitto:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"
    networks:
      smart-home:
        ipv4_address: 192.168.55.11
#    healthcheck:
#      test: [ "CMD", "ping", "-w", "5", "mosquitto"]
#      interval: 5s
#      timeout: 6s
#      retries: 1

  zigbee2mqtt:
    depends_on:
      mqtt:
        condition: service_started
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - /volume1/smart-home/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      TZ: Europe/Warsaw
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
    networks:
      web:
      smart-home:
        ipv4_address: 192.168.55.12

